CREATE TABLE "whale_alert" ( 
"row_id" INTEGER PRIMARY KEY AUTOINCREMENT,
"create_date" TEXT, 
"Whale Alert Species" TEXT, 
"Number Sighted" REAL, 
"Whale Alert Other Species" TEXT, 
"device_bearing" REAL, 
"device_latitude" REAL, 
"device_longitude" REAL, 
"Latitude" REAL,
"Longitude" REAL, 
"trip_id" INTEGER, 
"Comments" TEXT, 
"id" INTEGER, 
"lat" REAL, 
"lon" REAL, 
"number_sighted" INTEGER, 
"photos" TEXT, 
"species" TEXT, 
"Animal Status" TEXT,
"url" TEXT,
"Whale Alert Submitter Name" TEXT, 
"Whale Alert Submitter Phone" TEXT,
"Whale Alert Submitter Email" TEXT,
"wkt" TEXT
) 
