CREATE TABLE "sightings" ( 
"row_id" INTEGER PRIMARY KEY AUTOINCREMENT,
"create_date" TEXT, 
"CINMS Behavior" TEXT, 
"CINMS Photo Log" TEXT, 
"CINMS Species" TEXT, 
"Calves Sighted" INTEGER, 
"Certainty" TEXT, 
"Distance Category" TEXT, 
"Number Sighted" REAL, 
"Total Sighted (Including Calves)" INTEGER, 
"Other Vessels On Scene" INTEGER, 
"Other Species" TEXT,
"device_bearing" REAL, 
"device_latitude" REAL, 
"device_longitude" REAL, 
"trip_id" INTEGER, 
"Comments" TEXT, 
"id" INTEGER, 
"lat" REAL, 
"lon" REAL, 
"number_sighted" INTEGER, 
"photos" TEXT, 
"species" TEXT, 
"url" TEXT, 
"wkt" TEXT
) 
